### PR TITLE
[PLACES-379] Support configuration files

### PR DESCRIPTION
**Pull request by aiyan**
Thanks for taking a look at these changes. They primarily fall under the category of "quality-of-life improvements".

[Link to Jira task](https://pathcheck.atlassian.net/browse/PLACES-379?atlOrigin=eyJpIjoiMzgwYzczNTY4MTVlNGYwMmJjNTQ5NTQ3NmNhMTc1NmQiLCJwIjoiaiJ9).

## Motivation
The Safe Places backend uses about 30 environment variables. We can shift some of variables which require frequent configuration and/or do not require sensitivity to a user-friendly configuration file.

This also allows more flexible configuration formats, such as using arrays, which is difficult to support using en environment variable.

## Some notable changes
- New template configuration file
- New configuration schema
- New utility for reading the configuration and loading it into memory (throws helpful errors if something is wrong)
  - This is located at `/tools/config` and is well-documented.
- Functionality for CORS allowed origins for later use (currently commented out)

I believe these changes are fully backwards-compatible - no old environment variables were moved to the configuration file. Only a new, currently unused `allowedOrigins` setting is added.

Please read the [configuration guide](https://github.com/Path-Check/safeplaces-backend/blob/aab10be3e853154c9be0535ef85cd414ea247477/CONFIGURATION.md) for more detailed information about this enhancement.

## Some design decisions
- The configuration is not passed around as a constant. Instead, it is retrieved on-the-fly by importing `/tools/config` and running the `config.get()` function. The hope was to prevent a messy tree of passing down a configuration object.
- The YAML format was chosen instead of JSON because it seems more user-friendly and more human-readable
- By default, the utility looks for a configuration file named `config.yaml` at the server root. Another path can be specified by passing the `--config=/path/to/config/file.yaml` flag to the server.

If there exists any possible improvements over the above, let's change it!

## Tests
image

### CODE REVIEW

**Comment by sherifkozman** [comment]
@sublet @MarshallMcCoy i dont see the value of switching from env to yaml as they will both get created at runtime within any deployment workflow.
@aiyan

**Comment by MarshallMcCoy** [comment]
@aiyan talked with @sherifkozman earlier this morning. We've got a stable server setup and are close to releases with a number of HAs. For those reasons, let's shelve this for a little while and follow up with it once we've got a few deployments under our belts.

**Comment by aiyan** [comment]
@MarshallMcCoy The environment variables block cookie-based authentication, so I suppose we'll have to postpone that as well?

**Comment by aiyan** [comment]
I caught up with @sherifkozman and @MarshallMcCoy on this. We are postponing the adoption of this until after MVP1, as we found a way to unblock ourselves on issues related to config. 🥳

**Comment by MarshallMcCoy** [comment]
@aiyan can we go ahead and close this for now?

**Comment by aiyan** [comment]
@MarshallMcCoy Yep

**Pull request closed without merging**
